<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWindowsForms>False</UseWindowsForms>
    <ApplicationIcon>img\MainIcon.ico</ApplicationIcon>
    <RepositoryUrl>https://github.com/ibroomallaz/Desktop-Support</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <AssemblyVersion>4.2.0</AssemblyVersion>
    <FileVersion>4.2.1093</FileVersion>
    <Version>4.2.0-RC3</Version>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Title>Desktop Support App</Title>
    <Product>Desktop Support App</Product>
    <Description>Tools for UITS Desktop Support</Description>
    <Company>University of Arizona</Company>
    <Authors>Isaac Broomall</Authors>
    <AssemblyName>Desktop Support App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="img\fileicon.png" />
    <None Remove="img\icons\HomeIcon.png" />
    <None Remove="img\icons\QuickLinksInfo.png" />
    <None Remove="img\icons\SettingsIcon.png" />
    <None Remove="img\icons\UserViewIcon.png" />
    <None Remove="MVVM\View\fileicon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="img\MainIcon.ico" />
    <Resource Include="img\fileicon.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="img\icons\" />
    <Folder Include="MVVM\Model\Schemas\News\" />
  </ItemGroup>
</Project>
