//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSAMVVM.MVVM.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSAMVVM.MVVM.View.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Arizona • Desktop Support &amp; IT Services.
        /// </summary>
        public static string About_AppSubtitle {
            get {
                return ResourceManager.GetString("About_AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Support App.
        /// </summary>
        public static string About_AppTitle {
            get {
                return ResourceManager.GetString("About_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string About_Button_Email {
            get {
                return ResourceManager.GetString("About_Button_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Data.
        /// </summary>
        public static string About_Button_OpenAppData {
            get {
                return ResourceManager.GetString("About_Button_OpenAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs.
        /// </summary>
        public static string About_Button_OpenLogs {
            get {
                return ResourceManager.GetString("About_Button_OpenLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check failed.
        /// </summary>
        public static string About_CheckFailed {
            get {
                return ResourceManager.GetString("About_CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string About_Copy {
            get {
                return ResourceManager.GetString("About_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string About_Developers_Title {
            get {
                return ResourceManager.GetString("About_Developers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code &amp; issues.
        /// </summary>
        public static string About_Doc_GitHub_Desc {
            get {
                return ResourceManager.GetString("About_Doc_GitHub_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        public static string About_Doc_GitHub_Title {
            get {
                return ResourceManager.GetString("About_Doc_GitHub_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change log &amp; history.
        /// </summary>
        public static string About_Doc_ReleaseNotes_Desc {
            get {
                return ResourceManager.GetString("About_Doc_ReleaseNotes_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string About_Doc_ReleaseNotes_Title {
            get {
                return ResourceManager.GetString("About_Doc_ReleaseNotes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides &amp; documentation.
        /// </summary>
        public static string About_Doc_SharePoint_Desc {
            get {
                return ResourceManager.GetString("About_Doc_SharePoint_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project SharePoint.
        /// </summary>
        public static string About_Doc_SharePoint_Title {
            get {
                return ResourceManager.GetString("About_Doc_SharePoint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation &amp; Resources.
        /// </summary>
        public static string About_Documentation_Title {
            get {
                return ResourceManager.GetString("About_Documentation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Arizona • Desktop Support Application.
        /// </summary>
        public static string About_Footer {
            get {
                return ResourceManager.GetString("About_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture:.
        /// </summary>
        public static string About_Label_Architecture {
            get {
                return ResourceManager.GetString("About_Label_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device:.
        /// </summary>
        public static string About_Label_Device {
            get {
                return ResourceManager.GetString("About_Label_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory:.
        /// </summary>
        public static string About_Label_Directory {
            get {
                return ResourceManager.GetString("About_Label_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Edition:.
        /// </summary>
        public static string About_Label_OsEdition {
            get {
                return ResourceManager.GetString("About_Label_OsEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime:.
        /// </summary>
        public static string About_Label_Runtime {
            get {
                return ResourceManager.GetString("About_Label_Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UArizona.
        /// </summary>
        public static string About_OrgBadge {
            get {
                return ResourceManager.GetString("About_OrgBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System &amp; Diagnostics.
        /// </summary>
        public static string About_SystemDiagnostics_Title {
            get {
                return ResourceManager.GetString("About_SystemDiagnostics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy version string to clipboard.
        /// </summary>
        public static string About_Tooltip_CopyVersion {
            get {
                return ResourceManager.GetString("About_Tooltip_CopyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle detailed build / file version.
        /// </summary>
        public static string About_Tooltip_ToggleVersion {
            get {
                return ResourceManager.GetString("About_Tooltip_ToggleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        public static string About_UpToDate {
            get {
                return ResourceManager.GetString("About_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support App.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Note.
        /// </summary>
        public static string Feedback_AddNote {
            get {
                return ResourceManager.GetString("Feedback_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug.
        /// </summary>
        public static string Feedback_ReportBug {
            get {
                return ResourceManager.GetString("Feedback_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Feature.
        /// </summary>
        public static string Feedback_RequestFeature {
            get {
                return ResourceManager.GetString("Feedback_RequestFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Support Team.
        /// </summary>
        public static string Feedback_UpdateSupportTeam {
            get {
                return ResourceManager.GetString("Feedback_UpdateSupportTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Home_Button_TestDc {
            get {
                return ResourceManager.GetString("Home_Button_TestDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent searches in this session.
        /// </summary>
        public static string Home_RecentActivity_Empty {
            get {
                return ResourceManager.GetString("Home_RecentActivity_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to · Quick Jump.
        /// </summary>
        public static string Home_RecentActivity_Subtitle {
            get {
                return ResourceManager.GetString("Home_RecentActivity_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string Home_RecentActivity_Title {
            get {
                return ResourceManager.GetString("Home_RecentActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Mascot.
        /// </summary>
        public static string Home_ServiceMeow_Badge {
            get {
                return ResourceManager.GetString("Home_ServiceMeow_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Desktop Support! Mascot data is standing by..
        /// </summary>
        public static string Home_ServiceMeow_DefaultBlurb {
            get {
                return ResourceManager.GetString("Home_ServiceMeow_DefaultBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 ServiceMeow.
        /// </summary>
        public static string Home_ServiceMeow_Header {
            get {
                return ResourceManager.GetString("Home_ServiceMeow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading mascot of the day....
        /// </summary>
        public static string Home_ServiceMeow_PlaceholderBlurb {
            get {
                return ResourceManager.GetString("Home_ServiceMeow_PlaceholderBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Pet.
        /// </summary>
        public static string Home_ServiceMeow_SubmitPet {
            get {
                return ResourceManager.GetString("Home_ServiceMeow_SubmitPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Manage Shortcuts in Settings....
        /// </summary>
        public static string Home_Shortcuts_AddManage {
            get {
                return ResourceManager.GetString("Home_Shortcuts_AddManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced....
        /// </summary>
        public static string Home_Shortcuts_Advanced {
            get {
                return ResourceManager.GetString("Home_Shortcuts_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string Home_Shortcuts_Customize {
            get {
                return ResourceManager.GetString("Home_Shortcuts_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Home_Shortcuts_Done {
            get {
                return ResourceManager.GetString("Home_Shortcuts_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Shortcuts.
        /// </summary>
        public static string Home_Shortcuts_Title {
            get {
                return ResourceManager.GetString("Home_Shortcuts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD:.
        /// </summary>
        public static string Home_Status_AdLabel {
            get {
                return ResourceManager.GetString("Home_Status_AdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entra:.
        /// </summary>
        public static string Home_Status_EntraLabel {
            get {
                return ResourceManager.GetString("Home_Status_EntraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing domain controllers....
        /// </summary>
        public static string Home_Status_ProbingDc {
            get {
                return ResourceManager.GetString("Home_Status_ProbingDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick access dashboard and environment status.
        /// </summary>
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open shortcut manager in Settings.
        /// </summary>
        public static string Home_Tooltip_AdvancedShortcuts {
            get {
                return ResourceManager.GetString("Home_Tooltip_AdvancedShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Mascot.
        /// </summary>
        public static string Home_Tooltip_NextMascot {
            get {
                return ResourceManager.GetString("Home_Tooltip_NextMascot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Mascot Photo.
        /// </summary>
        public static string Home_Tooltip_ReloadMascot {
            get {
                return ResourceManager.GetString("Home_Tooltip_ReloadMascot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove shortcut.
        /// </summary>
        public static string Home_Tooltip_RemoveShortcut {
            get {
                return ResourceManager.GetString("Home_Tooltip_RemoveShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Active Directory Domain Controllers.
        /// </summary>
        public static string Home_Tooltip_TestDc {
            get {
                return ResourceManager.GetString("Home_Tooltip_TestDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string JumpList_Category_Application {
            get {
                return ResourceManager.GetString("JumpList_Category_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string JumpList_Category_Resources {
            get {
                return ResourceManager.GetString("JumpList_Category_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string JumpList_Category_Search {
            get {
                return ResourceManager.GetString("JumpList_Category_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force a check for application updates.
        /// </summary>
        public static string JumpList_CheckUpdates_Desc {
            get {
                return ResourceManager.GetString("JumpList_CheckUpdates_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string JumpList_CheckUpdates_Title {
            get {
                return ResourceManager.GetString("JumpList_CheckUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful Links and locations.
        /// </summary>
        public static string JumpList_QuickLinks_Desc {
            get {
                return ResourceManager.GetString("JumpList_QuickLinks_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string JumpList_QuickLinks_Title {
            get {
                return ResourceManager.GetString("JumpList_QuickLinks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup device details.
        /// </summary>
        public static string JumpList_SearchComputers_Desc {
            get {
                return ResourceManager.GetString("JumpList_SearchComputers_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Computers.
        /// </summary>
        public static string JumpList_SearchComputers_Title {
            get {
                return ResourceManager.GetString("JumpList_SearchComputers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup MIM groups and Dept Support.
        /// </summary>
        public static string JumpList_SearchGroups_Desc {
            get {
                return ResourceManager.GetString("JumpList_SearchGroups_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Groups.
        /// </summary>
        public static string JumpList_SearchGroups_Title {
            get {
                return ResourceManager.GetString("JumpList_SearchGroups_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup user attributes, licenses, and groups.
        /// </summary>
        public static string JumpList_SearchUsers_Desc {
            get {
                return ResourceManager.GetString("JumpList_SearchUsers_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        public static string JumpList_SearchUsers_Title {
            get {
                return ResourceManager.GetString("JumpList_SearchUsers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure application preferences.
        /// </summary>
        public static string JumpList_Settings_Desc {
            get {
                return ResourceManager.GetString("JumpList_Settings_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string JumpList_Settings_Title {
            get {
                return ResourceManager.GetString("JumpList_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick access to common university portals and team resources.
        /// </summary>
        public static string Links_Banner_Subtitle {
            get {
                return ResourceManager.GetString("Links_Banner_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links Directory.
        /// </summary>
        public static string Links_Banner_Title {
            get {
                return ResourceManager.GetString("Links_Banner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Links.
        /// </summary>
        public static string Links_Button_Reload {
            get {
                return ResourceManager.GetString("Links_Button_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No links found for this team.
        /// </summary>
        public static string Links_Empty_NoTeamLinks {
            get {
                return ResourceManager.GetString("Links_Empty_NoTeamLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Links.
        /// </summary>
        public static string Links_Section_CommonLinks {
            get {
                return ResourceManager.GetString("Links_Section_CommonLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Links_Section_Team {
            get {
                return ResourceManager.GetString("Links_Section_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University-wide.
        /// </summary>
        public static string Links_Section_UniversityWide {
            get {
                return ResourceManager.GetString("Links_Section_UniversityWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL to clipboard.
        /// </summary>
        public static string Links_Tooltip_CopyUrl {
            get {
                return ResourceManager.GetString("Links_Tooltip_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open link in default browser.
        /// </summary>
        public static string Links_Tooltip_OpenBrowser {
            get {
                return ResourceManager.GetString("Links_Tooltip_OpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force refresh links data.
        /// </summary>
        public static string Links_Tooltip_Reload {
            get {
                return ResourceManager.GetString("Links_Tooltip_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Nav_Admin {
            get {
                return ResourceManager.GetString("Nav_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Nav_Computer {
            get {
                return ResourceManager.GetString("Nav_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entra.
        /// </summary>
        public static string Nav_Entra {
            get {
                return ResourceManager.GetString("Nav_Entra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Nav_Groups {
            get {
                return ResourceManager.GetString("Nav_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Nav_Links {
            get {
                return ResourceManager.GetString("Nav_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Nav_User {
            get {
                return ResourceManager.GetString("Nav_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Mascot (ServiceMeow).
        /// </summary>
        public static string Settings_Mascot_CardTitle {
            get {
                return ResourceManager.GetString("Settings_Mascot_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Arizona Desktop Support pet mascot on the Home dashboard. When disabled, background pet synchronization and image downloads are stopped, and the Home dashboard expands to a clean full-width layout..
        /// </summary>
        public static string Settings_Mascot_Description {
            get {
                return ResourceManager.GetString("Settings_Mascot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ServiceMeow Mascot on Home Dashboard.
        /// </summary>
        public static string Settings_Mascot_EnableCheckbox {
            get {
                return ResourceManager.GetString("Settings_Mascot_EnableCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search (Overlay).
        /// </summary>
        public static string Settings_QuickSearch_CardTitle {
            get {
                return ResourceManager.GetString("Settings_QuickSearch_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Tap Key.
        /// </summary>
        public static string Settings_QuickSearch_DoubleTapKey {
            get {
                return ResourceManager.GetString("Settings_QuickSearch_DoubleTapKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Double-Tap Quick Search.
        /// </summary>
        public static string Settings_QuickSearch_EnableCheckbox {
            get {
                return ResourceManager.GetString("Settings_QuickSearch_EnableCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search History.
        /// </summary>
        public static string Settings_SearchHistory_CardTitle {
            get {
                return ResourceManager.GetString("Settings_SearchHistory_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History size.
        /// </summary>
        public static string Settings_SearchHistory_SizeLabel {
            get {
                return ResourceManager.GetString("Settings_SearchHistory_SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UArizona.
        /// </summary>
        public static string Splash_OrgBadge {
            get {
                return ResourceManager.GetString("Splash_OrgBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates….
        /// </summary>
        public static string Splash_Status_CheckingUpdates {
            get {
                return ResourceManager.GetString("Splash_Status_CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading services….
        /// </summary>
        public static string Splash_Status_LoadingServices {
            get {
                return ResourceManager.GetString("Splash_Status_LoadingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings….
        /// </summary>
        public static string Splash_Status_LoadingSettings {
            get {
                return ResourceManager.GetString("Splash_Status_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting….
        /// </summary>
        public static string Splash_Status_Starting {
            get {
                return ResourceManager.GetString("Splash_Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Arizona • Desktop Support &amp; IT Services.
        /// </summary>
        public static string Splash_Subtitle {
            get {
                return ResourceManager.GetString("Splash_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Support App.
        /// </summary>
        public static string Splash_Title {
            get {
                return ResourceManager.GetString("Splash_Title", resourceCulture);
            }
        }
    }
}
