//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSAMVVM.MVVM.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSAMVVM.MVVM.View.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support App.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Support App.
        /// </summary>
        public static string Splash_Title {
            get {
                return ResourceManager.GetString("Splash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UArizona.
        /// </summary>
        public static string Splash_OrgBadge {
            get {
                return ResourceManager.GetString("Splash_OrgBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Arizona • Desktop Support &amp; IT Services.
        /// </summary>
        public static string Splash_Subtitle {
            get {
                return ResourceManager.GetString("Splash_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting….
        /// </summary>
        public static string Splash_Status_Starting {
            get {
                return ResourceManager.GetString("Splash_Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates….
        /// </summary>
        public static string Splash_Status_CheckingUpdates {
            get {
                return ResourceManager.GetString("Splash_Status_CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading services….
        /// </summary>
        public static string Splash_Status_LoadingServices {
            get {
                return ResourceManager.GetString("Splash_Status_LoadingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings….
        /// </summary>
        public static string Splash_Status_LoadingSettings {
            get {
                return ResourceManager.GetString("Splash_Status_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug.
        /// </summary>
        public static string Feedback_ReportBug {
            get {
                return ResourceManager.GetString("Feedback_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Feature.
        /// </summary>
        public static string Feedback_RequestFeature {
            get {
                return ResourceManager.GetString("Feedback_RequestFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Support Team.
        /// </summary>
        public static string Feedback_UpdateSupportTeam {
            get {
                return ResourceManager.GetString("Feedback_UpdateSupportTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Note.
        /// </summary>
        public static string Feedback_AddNote {
            get {
                return ResourceManager.GetString("Feedback_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Nav_User {
            get {
                return ResourceManager.GetString("Nav_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Nav_Computer {
            get {
                return ResourceManager.GetString("Nav_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Nav_Groups {
            get {
                return ResourceManager.GetString("Nav_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entra.
        /// </summary>
        public static string Nav_Entra {
            get {
                return ResourceManager.GetString("Nav_Entra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Nav_Links {
            get {
                return ResourceManager.GetString("Nav_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Nav_Admin {
            get {
                return ResourceManager.GetString("Nav_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string JumpList_Category_Search {
            get {
                return ResourceManager.GetString("JumpList_Category_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string JumpList_Category_Resources {
            get {
                return ResourceManager.GetString("JumpList_Category_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string JumpList_Category_Application {
            get {
                return ResourceManager.GetString("JumpList_Category_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        public static string JumpList_SearchUsers_Title {
            get {
                return ResourceManager.GetString("JumpList_SearchUsers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup user attributes, licenses, and groups.
        /// </summary>
        public static string JumpList_SearchUsers_Desc {
            get {
                return ResourceManager.GetString("JumpList_SearchUsers_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Computers.
        /// </summary>
        public static string JumpList_SearchComputers_Title {
            get {
                return ResourceManager.GetString("JumpList_SearchComputers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup device details.
        /// </summary>
        public static string JumpList_SearchComputers_Desc {
            get {
                return ResourceManager.GetString("JumpList_SearchComputers_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Groups.
        /// </summary>
        public static string JumpList_SearchGroups_Title {
            get {
                return ResourceManager.GetString("JumpList_SearchGroups_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup MIM groups and Dept Support.
        /// </summary>
        public static string JumpList_SearchGroups_Desc {
            get {
                return ResourceManager.GetString("JumpList_SearchGroups_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string JumpList_QuickLinks_Title {
            get {
                return ResourceManager.GetString("JumpList_QuickLinks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful Links and locations.
        /// </summary>
        public static string JumpList_QuickLinks_Desc {
            get {
                return ResourceManager.GetString("JumpList_QuickLinks_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string JumpList_CheckUpdates_Title {
            get {
                return ResourceManager.GetString("JumpList_CheckUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force a check for application updates.
        /// </summary>
        public static string JumpList_CheckUpdates_Desc {
            get {
                return ResourceManager.GetString("JumpList_CheckUpdates_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string JumpList_Settings_Title {
            get {
                return ResourceManager.GetString("JumpList_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure application preferences.
        /// </summary>
        public static string JumpList_Settings_Desc {
            get {
                return ResourceManager.GetString("JumpList_Settings_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search History.
        /// </summary>
        public static string Settings_SearchHistory_CardTitle {
            get {
                return ResourceManager.GetString("Settings_SearchHistory_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History size.
        /// </summary>
        public static string Settings_SearchHistory_SizeLabel {
            get {
                return ResourceManager.GetString("Settings_SearchHistory_SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Mascot (ServiceMeow).
        /// </summary>
        public static string Settings_Mascot_CardTitle {
            get {
                return ResourceManager.GetString("Settings_Mascot_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ServiceMeow Mascot on Home Dashboard.
        /// </summary>
        public static string Settings_Mascot_EnableCheckbox {
            get {
                return ResourceManager.GetString("Settings_Mascot_EnableCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Arizona Desktop Support pet mascot on the Home dashboard. When disabled, background pet synchronization and image downloads are stopped, and the Home dashboard expands to a clean full-width layout..
        /// </summary>
        public static string Settings_Mascot_Description {
            get {
                return ResourceManager.GetString("Settings_Mascot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search (Overlay).
        /// </summary>
        public static string Settings_QuickSearch_CardTitle {
            get {
                return ResourceManager.GetString("Settings_QuickSearch_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Double-Tap Quick Search.
        /// </summary>
        public static string Settings_QuickSearch_EnableCheckbox {
            get {
                return ResourceManager.GetString("Settings_QuickSearch_EnableCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Tap Key.
        /// </summary>
        public static string Settings_QuickSearch_DoubleTapKey {
            get {
                return ResourceManager.GetString("Settings_QuickSearch_DoubleTapKey", resourceCulture);
            }
        }
    }
}
